server:
  port: 9093

spring:
  zipkin:
    base-url: http://localhost:9110
  application:
    name: spring-cloud-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://122.14.208.111:9091/eureka/,http://122.14.209.213:9091/eureka/
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}:${eureka.instance.metadata-map.versions}
    metadata-map:
      versions: 2.0

feign:
  hystrix:
    enabled: true

ribbon:       
  MaxAutoRetriesNextServer: 1  ##重试服务的个数
  MaxAutoRetries: 0            ##访问当前服务的次数
  ConnectTimeout: 250
  ReadTimeout: 5000
  #OkToRetryOnAllOperations: true

#hystrix连接超时设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000

serviceBamboo:
  multiVersion: crm:3.3.5,spring-cloud-provider:3.0 #调用服务器的版本 用,间隔