server:
  port: 9094

spring:
  zipkin:
    base-url: http://123.58.4.18:9110/


serviceBamboo:
  multiVersion: crm:3.3.5,spring-cloud-consumer:1.0 #调用服务器的版本 用,间隔
  
ribbon:       
  MaxAutoRetriesNextServer: 2  ##重试服务的个数
  MaxAutoRetries: 0            ##访问当前服务的次数
  ConnectTimeout: 250
  ReadTimeout: 1000
  OkToRetryOnAllOperations: true

#hystrix连接超时设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000





#设置日志级别，打印mybatis的日志
logging:
  level:
    #root: debug
    root: info

feign:
  hystrix:
    enabled: true
